- hosts: all
  gather_facts: yes
  become: yes
  vars_prompt:
    - name: "backup"
      prompt: "Would you like to update a validator node? (yes/no)"
      private: no
    - name: "restore"
      prompt: "Would you like to update a writer node? (yes/no)"
      private: no
  roles:
    - lacchain-update-node
