- name: Download health-check source code
  git:
        repo: "https://github.com/lacchain/node-health-check.git"
        dest: "/root/go/src/healthCheck" 

- name: install health-dependencies for {{ ansible_distribution }}
  yum:
   name: "{{ item }}"
  with_items:
   - "systemd-devel"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')

- name: Build health check executable program
  shell: export GO111MODULE=off && go get ./... && go build -o health-check
  args:
    chdir: "/root/go/src/healthCheck"