- name: Create nginx ssl directory
  file:
    path: ~/lacchain/nginx
    state: directory
    mode: '0644'
    force: yes

- name: Create private directory
  file:
    path: /etc/ssl/private
    state: directory
    mode: '0644'
    force: no

- name: generate configuration openssl file
  template:
    src: "openssl.j2"
    dest: "~/lacchain/nginx/openssl.cnf"
    force: yes

- name: Create self signed certificate
  shell: openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=US/ST=Washington/L=Seatle/O=Lacchain/OU=Network/CN={{dns_name}}" -config /root/lacchain/nginx/openssl.cnf
  become: yes

- name: Create Diffie Hellman Group
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  become: yes