---
- name: Health Check
  debug:
    msg: Configuring Health Check Service

- name: create Health Check directory
  file:
    path: "/root/lacchain/health-check"
    mode: "0755"
    state: directory

- name: Move executable health-check program
  shell: mv /root/go/src/healthCheck/health-check /root/lacchain/health-check/
  args:
    warn: false

- name: Copy service file to systemd
  copy:
    src: "{{ role_path }}/files/health-check.service"
    dest: /lib/systemd/system/health-check.service
    mode: 0775

- name: Reload systemctl daemon
  shell: systemctl daemon-reload
  args:
    warn: false    

- name: Enable service Health-Check
  service:
    name: health-check
    enabled: yes

- name: Start Health check service
  service:
    name: health-check
    state: restarted