---
- name: Install pantheon
  debug:
        msg: "Installing Pantheon"

- name: Download pantheon source code
  git:
        repo: "https://github.com/PegaSysEng/pantheon.git"
        dest: "/tmp/pantheon"
        version: a8ea12a8379a7951b2e940bc8a9f1568c805ef4e

- name: Building Pantheon
  shell: "sh ./gradlew build -x test"
  args:
        chdir: /tmp/pantheon/

- name: Extract the Pantheon tarball
  unarchive:
        src: "/tmp/pantheon/build/distributions/pantheon-1.2.0.tar.gz"
        dest: /usr/local
        copy: no

- name: Symbolic link for pantheon
  file:
        src: "/usr/local/pantheon-1.2.0/bin/{{ item.src }}"
        dest: "/usr/bin/{{ item.dest }}"
        state: link
  with_items:
        - { src: "pantheon", dest: "pantheon" }
        - { src: "pantheon.bat", dest: "pantheon.bat" }
