---
# tasks file for docker-ce-ansible-role

- name: Remove previous docker installation
  apt:
    name: "{{ docker_cleanup_packages_Ubuntu }}"
    state: absent

- name: Install prerequisite packages
  apt:
    name: "{{ docker_prerequisite_packages_Ubuntu }}"
    state: present

- name: Install prerequisite packages (for Ubuntu 14.04 only)
  apt:
    name: "{{ docker_prerequisite_packages_Ubuntu_1404 }}"
    state: present
  when: ansible_distribution_version == "14.04"

- name: Import Docker CE repository gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes
