- name: Get java version
  shell: ls | grep "jdk-11" | grep "_linux-x64_bin.rpm"
  args:
    chdir: "{{oracle_java_dir_source}}"
  register: oracle_java_rpm_filename

- name: Print found Java version
  debug: 
    msg: "Found java version: {{ oracle_java_rpm_filename.stdout}}"


- name: install java
  package:
    name="{{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename.stdout }}"
    state=present
  become: yes