---
 - name: download epel repository
   get_url:
    url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    dest: "/tmp/epel-release-latest-7.noarch.rpm"

 - name: install epel repository
   yum:
    name: "/tmp/epel-release-latest-7.noarch.rpm"

 - name: install dependencies for {{ ansible_distribution }}
   yum:
    name: "{{ item }}"
   with_items:
    - "*"
    - "gmp-devel"
    - "gcc"
    - "gcc-c++"
    - "make"
    - "openssl-devel"
    - "libdb-devel"
    - "ncurses-devel"
    - "wget"
    - "nmap-ncat"
    - "libsodium-devel"
    - "libdb-devel"
    - "leveldb-devel"
    - "git"