---
# Installing libsodium
- name: Download libsodium tar
  get_url:
        url: "{{libsodium_base_url}}/{{libsodium_version}}"
        dest: "/tmp/{{libsodium_version}}"
        mode: 0440

- name: Extract the libsodium tarball
  unarchive:
        src: "/tmp/{{libsodium_version}}"
        dest: /usr/local
        copy: no

- name: "Installing libsodium"
  shell: sh ./configure && make && make check && make install
  args:
        chdir: "/usr/local/libsodium-stable"
