---
- name: download leveldb
  get_url:
    url: "{{leveldburi}}/{{leveldb_version}}/sha512/{{ leveldbtempnumber }}/{{leveldb_version}}"
    dest: "/tmp/{{leveldb_version}}"

- name: Extract leveldb
  unarchive:
    src: "/tmp/{{leveldb_version}}"
    dest: "/tmp"
    copy: no

- name: Set command Shell
  lineinfile:
    path: /tmp/{{leveldb_release}}/Makefile
    regexp: '^(.*)./build_detect_platform(.*)$'
    line: '    sh ./build_detect_platform build_config.mk ./)'
    backrefs: yes

- name: make leveldb
  shell: make
  args:
    chdir: "/tmp/{{leveldb_release}}"

- name: move ibleveldb.*
  copy:
    src: "/tmp/{{leveldb_release}}/out-static/{{ item }}"
    dest: "/usr/local/lib"
    remote_src: yes
  with_items:
    - libleveldb.a
    - libmemenv.a

- name: move ibleveldb.*
  copy:
    src: "/tmp/{{leveldb_release}}/out-shared/{{ item }}"
    dest: "/usr/local/lib"
    remote_src: yes
  with_items:
    - libleveldb.so.1.20
    - libleveldb.so
    - libleveldb.so.1

#- name: symbolic link for liblevel
#  file:
#    src: "/usr/local/lib/libleveldb.so.1.9"
#    dest: "/usr/local/lib/{{ item }}"
#    state: link
#  with_items:
#    - "libleveldb.so"
#    - "libleveldb.so.1"

- name: move leveldb folder
  command: "cp -R leveldb /usr/local/lib"
  args:
    chdir: "/tmp/{{leveldb_release}}/include"
  notify: run ldconfig

- meta: flush_handlers
