- name: Download health-check source code
  git:
        repo: "https://github.com/eum602/healthCheck.git"
        dest: "/root/go/src/github/healthCheck"

- name: Build health check executable program
  shell: go get ./... && go build health-check.go
  args:
    chdir: "/root/go/src/github/healthCheck"

- name: Renaming
  shell: mv health-check healthCheckexe
  args:
    chdir: "/root/go/src/github/healthCheck"