- name: install nginx prerequisites
  package:
    name: yum-utils
    state: present

- name: Setup nginx repository
  copy:
    src: "{{ role_path }}/files/nginx.repo"
    dest: /etc/yum.repos.d
    mode: 0644

- name: install nginx
  package:
    name: nginx
    state: present
    disable_gpg_check: yes
  