---
- name: Install nginx for {{ ansible_distribution }}
  import_tasks: "install-nginx-ubuntu.yml"
  when: ansible_distribution |lower == 'ubuntu'

- name: Install nginx for {{ ansible_distribution }}
  import_tasks: "install-nginx-rhel.yml"
  when: (ansible_distribution |lower == 'redhat') or (ansible_distribution |lower == 'centos')

- name: Configure nginx
  import_tasks: "configure-nginx.yml"